# Standard packages
brew 'coreutils'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'goaccess'
brew 'httpie'
brew 'jq'
brew 'kubectl'
brew 'k9s'
brew 'ncdu'
brew 'nvim'
brew 'openvpn'
brew 'pnpm'
brew 'redis'
brew 'tmux'
brew 'wget'
brew 'wireguard-tools'
brew 'zsh'

# Cask appllications
cask 'brave-browser'
cask 'claude'
cask 'keepassxc'
cask 'obsidian'
cask 'rectangle'
cask 'shifty'
cask 'stats'
cask 'whatsapp'

# Fonts
cask 'font-fira-mono'
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'font-jetbrains-mono-nerd-font'
